name: Get ticket number from branch name

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  get-ticket-number:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Get branch name
        run: |
          branch_name=${{ github.head_ref }}
          ticket_number=$(echo "$branch_name" | sed 's/[^0-9]*//g' | sed -r 's/([0-9]+)/OPS-\1/gI')
          echo "The ticket number is $ticket_number"
