name: Extract Jira Ticket Number
on:
  pull_request:
    types: [opened]

jobs:
  extract-ticket:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Get Jira Ticket Number
      id: get_ticket
      run: |
        branch=$(echo $GITHUB_REF | sed 's/refs\/heads\///')
        ticket=$(echo $branch | grep -oP "(?<=^|\/)[A-Z]+-[0-9]+(?=$|\/)")
        echo "::set-output name=ticket::$ticket"
        echo "Jira ticket Number: $ticket"
