name: Get branch name from pull request

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  get-branch-name:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Get branch name
        run: echo "The branch name is ${{ github.head_ref }}"
