name: Get ticket number from branch name

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  get-ticket-number:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Get branch name
        run: |
          branch_name=${{ github.head_ref }}
          ticket_number=$(echo "$branch_name" | sed 's/[^0-9]*//g' | sed -r 's/([0-9]+)/OPS-\1/gI')
          echo "The ticket number is $ticket_number"
          jira_ticket_status="$(curl -u "${{secrets.JIRA_USERNAME}}":"${{secrets.JIRA_API_KEY}}" -X GET -H "Content-Type: application/json" "https://${{secrets.JIRA_HOST}}/rest/api/2/issue/${jira_ticket}?fields=status" | jq '.fields.status.name')"
          echo Jira_status: "$jira_ticket_status"
