name: Extract Jira Ticket Number on Merge
on:
  pull_request:
    types: [opened, synchronize, reopened, edited, ready_for_review]
    branches:
      - main

jobs:
  extract-ticket-number:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    steps:
      - name: Extract Ticket Number
        uses: actions/github-script@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const branchName = context.payload.pull_request.head.ref;
            const ticketNumber = branchName.match(/(OPS-\d+)/)?.[1];
            console.log(`Ticket Number: ${ticketNumber}`);
