name: Get ticket number from branch name

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  get-ticket-number:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Get branch name
        run: |
          branch_name=${{ github.head_ref }}
          ticket_number=${branch_name:8:7}
          echo "The ticket number is $ticket_number"
