name: Extract Jira Ticket Number on PR Create
on:
  pull_request:
    types: [opened]

jobs:
  extract-ticket-number:
    runs-on: ubuntu-latest
    steps:
      - name: Extract Ticket Number
        uses: actions/github-script@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const branchName = context.payload.pull_request.head.ref;
            const ticketNumber = branchName.match(/(OPS-\d+)/)?.[1];
            console.log(`Ticket Number: ${ticketNumber}`);
