name: First-action-file
on:
  pull_request:
    types: [opened, synchronize, reopened, edited, ready_for_review]
    branches: [main]

jobs:
  jira-status-check:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        ref: ${{ github.head_ref }}
    - name: Extract JIRA ticket number
      run: |
        jira_ticket="$(echo "${{ github.event.pull_request.title }}")"
        echo "JIRA ticket number: $jira_ticket"
